accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('register', views.RegisterFormView.as_view(),{'next_page' :'trading:index'},name='register'),
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
]

tradingPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('tradings.urls', namespace='tradings')),
]

tradings/urls.py
from django.urls import path

from . import views

app_name = 'tradings'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category-detail'),
    path('categories/', views.CategoryList.as_view(), name='category-list'),
]

accounts/models.py
from django.db import models

# Create your models here.

tradings/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('tradings:category-detail', kwargs={'pk': self.pk})

    
    def __str__(self):
        return self.title
    


class Item(models.Model):
    title = models.CharField(max_length=20)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='items', null=True, on_delete=models.SET_NULL)


    def get_absolute_url(self):
        return reverse('tradings:item-detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.title
    

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import FormView


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = 'accounts/login'
    template_name = 'accounts/register.html'


    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

tradings/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from .models import Item, Category

# Create your views here.


class Index(TemplateView):
    template_name = 'tradings/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            context['items'] = Item.objects.filter(user=user)
        return context


class CategoryList(ListView):
    model = Category

class CategoryDetail(DetailView):
    model = Category

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <form method="POST">
        <h2>Please Sign in</h2>{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Log in</button>
        <a class="btn btn-primary" href="{% url 'accounts:register' %}">Sign up</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <form method="POST">
        <h2>Register</h2>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group
                {% if field.errors %} has-error {% endif %}">
                <label>{{ field.label }}</label>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Sign up</button>
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} TRADINGS {% endblock %}</title>
  <!-- fonts   -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <!-- styles cdn -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- local styles -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block nav %}
{% include 'tradings/navbar.html' %}
{% endblock nav %}

<div class="container">
  {% block content %}
  {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

tradings/templates/tradings/category_detail.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ object.title }}</h2>
    <ul class="list-group">
        {% for item in object.items.all %}
            <li class="list-group-item"><a href="#">{{ item.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

tradings/templates/tradings/category_list.html
{% extends 'base.html' %}
{% block content %}
    <ul class="list-group">
        {% for category in object_list %}
            <li class="list-group-item"><a href="{{ category.get_absolute_url  }}">{{ category.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

tradings/templates/tradings/index.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center">hello, {{ user.username }} from tradings app</h1>
    {% if items %}
        <ul class="list-group">
            {% for item in items %}
                <li class="list-group-item">{{item.title}}&nbsp;&ndash; {{item.category}}&nbsp;&ndash; {{item.user}}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>nothing here</h3>
    {% endif %}
{% else %}
    <h1 class="text-center">Hello, anonym user</h1>
    <p>please, register or login</p>
{% endif %}
{% endblock content %}

tradings/templates/tradings/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Tradings</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="nav-link" href="{% url 'tradings:category-list' %}">categories</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li class="nav-item my-auto">{{ user.get_username }}</li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout'%}?next={{request.path}}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login'%}?next={{request.path}}">
                Log in
              </a>
            </li>
        {% endif %}
      </ul>
  </div>
</nav>